const ActionType = {
  //GET  Products
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAIL: "FETCH_PRODUCT_FAIL",

  //Add  Product
  ADD_PRODUCT_START: "ADD_PRODUCT_START",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAIL: "ADD_PRODUCT_FAIL",

  //Update  Product
  UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",
  UPDATE_PRODUCT_START: "UPDATE_PRODUCT_START",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",

  //Delete  Product
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",
};
export default ActionType;
