const AuthActionType = {
  //Add USER
  ADD_USER_START: "ADD_USER_START",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAIL: "ADD_USER_FAIL",

  //Add LOGIN
  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

  // Logout
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",

  //Add ADDRESS
  ADD_ADDRESS_START: "ADD_ADDRESS_START",
  ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
  ADD_ADDRESS_FAIL: "ADD_ADDRESS_FAIL",
};
export default AuthActionType;
